### PR TITLE
employee list 

### LINKED ISSUE #3: User should be able to add an employee
## Acceptance Criteria

**Given** the user is viewing the list of employees
**When** the user clicks the Create New link
**Then** a form for be displayed on which the following information can be entered

1. First name
1. Last name
1. Employment start date
1. Select a department from a drop down

### PR DESCRIPTION
**Pull request by evanreynolds1116**
# Description

Employee list displays employee first name, last name, and department name.

Fixes # (issue)
## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Testing Instructions

To verify changes, run python manage.py runserver in your terminal and in your brower go to localhost:8000/employees

# Checklist:
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings or errors
- [x ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by mbrownlee — COMMENTED** [review]
👍

**Review by tannerb9 — APPROVED** [review]

**Comment by tannerb9** [comment]
👍

**Comment by mbrownlee** [comment]
👍

**Review by leigharobinson — APPROVED** [review]
I think this looks good! Way to go Even!

**Review by mbrownlee — APPROVED** [review]

**Pull request merged**
